# Generated by Django 4.2.10 on 2025-10-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applied_on',
            new_name='date_applied',
        ),
    ]
