sonar.projectKey=shri0612_job-application-tracker
sonar.organization=shri0612

sonar.projectName=Job Application Tracker
sonar.projectVersion=1.1

sonar.sources=.

sonar.exclusions=**/venv/**, **/migrations/**, **/static/**

sonar.tests=.
sonar.test.inclusions=**/tests.py, **/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
